FROM nginx
MAINTAINER chenpeng6@360.cn
ADD ./build /usr/share/nginx/html
ADD ./nginx.conf /etc/nginx/nginx.conf
ADD ./start.sh /root/viz/start.sh
ADD ./config.properties /root/viz/config.properties
RUN chmod -R 777 /root/viz/start.sh &&\
    chmod -R 777 /etc/nginx/nginx.conf &&\
    chmod -R 777 /usr/share/nginx/html

EXPOSE 80
ENTRYPOINT ["/root/viz/start.sh"]
